# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Python
tagline:             'Experiments'
description:         "Raghavan's Ramblings"
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

gems: 
    - jekyll-paginate
    - jekyll-terminal
